# Warning - this file is autogenerated by the configure script
# Do not edit
BISECT_ENABLE=NO
DISABLE_WARN_ERROR=false
VARPATCHDIR=/var/patch
ETCDIR=/etc/xensource
OPTDIR=/opt/xensource
PLUGINDIR=/etc/xapi.d/plugins
EXTENSIONDIR=/etc/xapi.d/extensions
HOOKSDIR=/etc/xapi.d
INVENTORY=/etc/xensource-inventory
XAPICONF=/etc/xapi.conf
LIBEXECDIR=/opt/xensource/libexec
SCRIPTSDIR=/etc/xensource/scripts
SHAREDIR=/opt/xensource
WEBDIR=/opt/xensource/www
CLUSTER_STACK_ROOT=/usr/libexec/xapi/cluster-stack
BINDIR=/opt/xensource/bin
SBINDIR=/opt/xensource/bin
UDEVDIR=/etc/udev
DOCDIR=/usr/share/xapi/doc
export BISECT_ENABLE DISABLE_WARN_ERROR VARPATCHDIR ETCDIR OPTDIR PLUGINDIR EXTENSIONDIR HOOKSDIR INVENTORY XAPICONF LIBEXECDIR SCRIPTSDIR SHAREDIR WEBDIR CLUSTER_STACK_ROOT BINDIR SBINDIR UDEVDIR DOCDIR
